### ISSUE TITLE
Release of numpy 2.0.0 cause error: numpy.dtype size changed, may indicate binary incompatibility

### ISSUE THREAD

**Issue by Mckay4242** [rawlik/makemedicom#8]
**Issue:**
The following error is encountered when running **makemedicom**:
`numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject`

**Reason:**
The reason is that pandas defines its numpy dependency freely as "anything newer than certain version of numpy". The problem occured, when numpy==2.0.0 has been released on **June 16th 2024**, because it is no longer compatible with the pandas version installed by pipx. Details here: [https://stackoverflow.com/questions/78634235/numpy-dtype-size-changed-may-indicate-binary-incompatibility-expected-96-from](https://stackoverflow.com/questions/78634235/numpy-dtype-size-changed-may-indicate-binary-incompatibility-expected-96-from)

**Solution:**
Specify the version of numpy and pandas for the installation with pipx. 

**Interim Solution:**

Run:

1. `pipx install makemedicom`
2. `pipx inject makemedicom numpy==1.26.4 --force`

**Comment by mrawlik** [comment]
Fixed in 0.0.8.
